spring:
  datasource:
    url: jdbc:mysql://10.179.208.58:3306/man_opph_policy?characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useDynamicCharsetInfo=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
